### ISSUE TITLE
Using without docker

### ISSUE THREAD

**Issue by delumerlino** [Blaok/nextcloud-inotifyscan#11]
Hi, is it possible to use without docker?
I have a lot of warnings while trying to run it:

nextcloud-inotifyscan@www-data.service - Nextcloud inotify scan daemon for www-data
   Loaded: loaded (/etc/systemd/system/nextcloud-inotifyscan@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-07-24 07:08:51 UTC; 14s ago
  Process: 4979 ExecStart=/usr/local/bin/nextcloud-inotifyscan --config /etc/nextcloud-inotifyscan/www-data.ini (code=exited, status=1/FAILURE)
 Main PID: 4979 (code=exited, status=1/FAILURE)

Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]: Traceback (most recent call last):
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:   File "/usr/local/bin/nextcloud-inotifyscan", line 279, in <module>
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:     main()
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:   File "/usr/local/bin/nextcloud-inotifyscan", line 274, in main
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:     for task in watch_instances(parse_args()):
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:   File "/usr/local/bin/nextcloud-inotifyscan", line 196, in watch_instances
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]:     min_interval = min(instance.interval for instance in instances)
Jul 24 07:08:51 nextcloud nextcloud-inotifyscan[4979]: ValueError: min() arg is an empty sequence
Jul 24 07:08:51 nextcloud systemd[1]: nextcloud-inotifyscan@www-data.service: Main process exited, code=exited, status=1/FAILURE
Jul 24 07:08:51 nextcloud systemd[1]: nextcloud-inotifyscan@www-data.service: Failed with result 'exit-code'.

Thanks

Andrea

**Comment by delumerlino** [comment]
I have worked a lot, it seems it does not work if LDAP is enabled:

In Connection.php line 209:

  Connection to LDAP server could not be established


group:list [-l|--limit [LIMIT]] [-o|--offset [OFFSET]] [--output [OUTPUT]]

Traceback (most recent call last):
  File "/usr/local/bin/nextcloud-inotifyscan", line 279, in <module>
    main()
  File "/usr/local/bin/nextcloud-inotifyscan", line 274, in main
    for task in watch_instances(parse_args()):
  File "/usr/local/bin/nextcloud-inotifyscan", line 179, in watch_instances
    universal_newlines=True))
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', 'group:list', '--output=json']' returned non-zero exit status 1

**Comment by Blaok** [comment]
I'm not sure why LDAP is preventing this script from working but I think you can bypass this problem by making `user` include one of the `applicable_users` of the external storage in the setting file. If you still cannot solve this problem, please consider posting your (sanitized) setting file in the issue and provide more information about your use case.

**Comment by delumerlino** [comment]
Hi, I have fixed and now it is working also with LDAP users.
How may I use inotifyscan for group folders?
And how may I trigger the event for sending emails on changed/added/deleted file and/or folder?

Thank you

**Comment by Blaok** [comment]
If you are talking about the [group folder app](https://github.com/nextcloud/groupfolders), I am not familiar with that and don't think it will work with the current version of this script. If it has a well-defined storage folder and the file database can be updated via `occ` commands, I think one can add the feature to support it. However, I do not have bandwidth to add new features in a new future, but any pull requests would be appreciated.

About triggers for sending emails, I think they are out of the scope of this project. Ideally they should be triggered by the updates of the database, which themselves can be triggered by this script, or Nextcloud's built-in scanning mechanism.

**Comment by Blaok** [comment]
Closing this as a dup of #27.
