### ISSUE TITLE
It can't scan subfolder in external storage

### ISSUE THREAD

**Issue by aldington-david** [Blaok/nextcloud-inotifyscan#15]
I creat a local  external storage for rclone and the inotify only scan the path in nextcloudsetting when I use cp in ssh.(not include subfolder)

**Comment by Blaok** [comment]
Are you expecting inotify to watch your remote storage mount via rclone? inotify is limited to local filesystems (e.g. ext4) and won't work with any remote mounts (e.g. NFS, ceph, fuse).
