### ISSUE TITLE
Differentiate between file changes

### ISSUE THREAD

**Issue by euh2** [Blaok/nextcloud-inotifyscan#16]
I'm looking at this project and want to adapt it to my kubernetes nextcloud cluster. But I wounder if this code does differentiate between files changed from within Nextcloud and outside changes? My reading of the code suggests it does not. 
This means inotify triggers occ files:scan.. on every change, even when i.e. upload a file through Nextcloud Web Interface. In this case Nextcloud already does update its Database, so this code just doubles the work.

Are my assumptions correct? Ideas on how to prevent this?

**Comment by Blaok** [comment]
You are right that changes made from within Nextcloud will also trigger scanning. According to the [man pages](https://linux.die.net/man/7/inotify),
> The inotify API provides no information about the user or process that triggered the inotify event. In particular, there is no easy way for a process that is monitoring events via inotify to distinguish events that it triggers itself from those that are triggered by other processes.

That said, I personally don't think scanning internal changes twice is a problem. The filesystem and the memory both have caches. Are you experiencing performance issues? If so, you probably have to modify inotify to make it return PID info.

**Comment by euh2** [comment]
It makes sense that the performance penalty is negligible. I haven't tested it yet though. Hopefully I will have something up and running in a few days. If it all works I will publish the code.
