### ISSUE TITLE
Doesn't seem to work with external mounts, looking for solutions

### ISSUE THREAD

**Issue by enselerizer** [Blaok/nextcloud-inotifyscan#26]
Hi. I'm looking for ways to make Nextcloud detect changes to local storage in my case. I am running a virtual machine with Debian 12, on a Windows 10 host system, with Nextcloud AIO installed on the guest OS. I want to have access to files directly on the Windows host, while Nextcloud sees this folder as local storage.

I mounted the folder on the windows host to /mnt/nextcloud via fstab, with the options "uid=33,gid=0,dmode=0750,fmode=0750". Next, I created an "ncdata" folder inside, which I mounted in Nextcloud AIO according to the official tutorial. As a result, I have access to the local storage on windows host and changes are detected if they are made from the guest OS. But if I create or change files on windows, the changes are not registered.

What solution should I use in this case?

**Comment by Blaok** [comment]
If the remote filesystem does not send notifications, there is no easy way to detect remote changes. It might be helpful if you can influence the filesystem behavior (e.g. by filing a feature request). My personal solution is to run Windows as guest and host the shared files on the Linux host and share to the Windows guest via virtiofs, in which case changes from the Windows guest will generate notifications and trigger incremental scans. Not sure if this is something doable in your use case.

**Comment by enselerizer** [comment]
After trying several options, I settled on the solution of simply running the Samba server in the guest OS, so this issue is irrelevant. But thanks for the advice. I have one more question, but I should probably open a separate topic for it.
