### ISSUE TITLE
Not working with docker = no 

### ISSUE THREAD

**Issue by thost96** [Blaok/nextcloud-inotifyscan#28]
Hi,

i've configured the _www-data.ini_ file with `docker = no` and no Docker isn't installed on the system, as the Nextcloud Installation isn't running on Containers. Starting the service or running manually failes with following error:

```
:~# /usr/local/bin/nextcloud-inotifyscan --config /etc/nextcloud-inotifyscan/www-data.ini
  File "/usr/local/bin/nextcloud-inotifyscan", line 36
    def __init__(self, docker: Optional[Tuple[str, str]]) -> None:
                             ^
SyntaxError: invalid syntax
```

**Comment by Blaok** [comment]
It looks like your Python does not support type annotation. Can you try a more recent Python (3.7+) or use an older commit (e.g. https://github.com/Blaok/nextcloud-inotifyscan/commit/a742b42ca7ced11a079478441880264685a0a0c9)?

**Comment by thost96** [comment]
Thanks for that hint. Python 3.9.2 and also Python 2.7.18 was both installed. I've removed Python 2.7 and relinked /usr/bin/python and now it's working. Thanks!
