### ISSUE TITLE
can't use with Univention Corporate Server and nextcloud

### ISSUE THREAD

**Issue by lirees** [Blaok/nextcloud-inotifyscan#8]
Hi

i have tried to use this tool with nextcloud installed by ucs system but i can't start the app because the docker don't have a systemctl startup and the command "sudo systemctl enable --now nextcloud-inotifyscan@username" fail. 

thanks

**Comment by Blaok** [comment]
All you need to do is to run `/usr/local/bin/nextcloud-inotifyscan --config /etc/nextcloud-inotifyscan/some.ini` as the user running nextcloud.

**Comment by lirees** [comment]
don't work ... if run this commad i give e lot of error :

root@nextc-96491634:/# /usr/local/bin/nextcloud-inotifyscan --config /etc/nextcloud-inotifyscan/www-data.ini
Traceback (most recent call last):
  File "/usr/local/bin/nextcloud-inotifyscan", line 279, in <module>
    main()
  File "/usr/local/bin/nextcloud-inotifyscan", line 274, in main
    for task in watch_instances(parse_args()):
  File "/usr/local/bin/nextcloud-inotifyscan", line 148, in watch_instances
    universal_newlines=True).rstrip()
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Blaok** [comment]
This means the subprocess is not properly created because it cannot find the executable. Please make sure `php` can be found in your `PATH`. If you are using docker, **meaning your are running nextcloud inside a docker but you are running this script outside of the docker**, please make sure `docker` can be found in your `PATH`. You can check if `which php` or `which docker` returns anything.

**Comment by lirees** [comment]
perfect .. it works great !!

thanks

**Comment by Blaok** [comment]
My pleasure.

**Comment by lirees** [comment]
i'm apologize to write you again but after restart of the ucs test machines the script don't run again, i don't understand that happened i have only i have make simply system restart... so i have do it all from scratch sure to solve but don't works .. i report all the steps 

1) install ucs update and nextcloud form umc
2) install inotifywait 
3) install nextcloud-inotifyscan
4) create www-data-ini in /etc/nextcloud-inotifyscan/
[DEFAULT]
interval = 1
[Instance1]
occ = occ
user = administrator
docker = www-data:a1e6050215ae
external_storage = yes

i have tried to use in the docker like user also root, the container id is retrieve from the command docker ps 

root@server:/etc/nextcloud-inotifyscan# docker ps
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS              PORTS                           NAMES
a1e6050215ae        docker.software-univention.de/nextcloud:15.0.7-0       "/bin/sh -c /usr/s..."   16 hours ago        Up 15 hours         0.0.0.0:40000->80/tcp           tender_joliot



5) check that all path are correct 
which docker > /usr/bin/docker
which php > /usr/bin/php
which python  > /usr/bin/python
which inotifywait >  /usr/bin/inotifywait

6) test the access to the docker container 
docker exec -it 1e6050215ae echo "Hello from container!"


7) and finally run sudo systemctl enable --now nextcloud-inotifyscan@www-data


if i check the systemctl status the service is stopped 


root@server:/etc/nextcloud-inotifyscan# sudo systemctl status  nextcloud-inotifyscan@www-data
â nextcloud-inotifyscan@www-data.service - Nextcloud inotify scan daemon for www-data
   Loaded: loaded (/etc/systemd/system/nextcloud-inotifyscan@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-05-15 06:11:34 CEST; 3min 53s ago
 Main PID: 20301 (code=exited, status=1/FAILURE)

mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File "/usr/local/bin/nextcloud-inotifyscan", line 279, in <module>
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:     main()
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File "/usr/local/bin/nextcloud-inotifyscan", line 274, in main
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:     for task in watch_instances(parse_args()):
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File "/usr/local/bin/nextcloud-inotifyscan", line 148, in watch_instances
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:     universal_newlines=True).rstrip()
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service: Main process exited, code=exited, status=1/FAILURE
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service: Unit entered failed state.
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service: Failed with result 'exit-code'.

i'm apologize but it's two day i fight without any result

Thanks

**Comment by lirees** [comment]
i'm apologize to write you again but after restart of the ucs test machines
the script don't run again, i don't understand that happened i have only i
have make simply system restart... so i have do it all from scratch sure to
solve but don't works .. i report all the steps

1) install ucs update and nextcloud form umc
2) install inotifywait
3) install nextcloud-inotifyscan
4) create www-data.ini in /etc/nextcloud-inotifyscan/
[DEFAULT]
interval = 1
[Instance1]
occ = occ
user = administrator
docker = www-data:a1e6050215ae
external_storage = yes

i have tried to use root as user and with file name root.ini, the container
id is retrieve from the command docker ps

root@server:/etc/nextcloud-inotifyscan# docker ps
CONTAINER ID        IMAGE
COMMAND                  CREATED             STATUS              PORTS
                     NAMES
a1e6050215ae        docker.software-univention.de/nextcloud:15.0.7-0
 "/bin/sh -c /usr/s..."   16 hours ago        Up 15 hours
 0.0.0.0:40000->80/tcp           tender_joliot



5) check that all path are correct
which docker > /usr/bin/docker
which php > /usr/bin/php
which python  > /usr/bin/python
which inotifywait >  /usr/bin/inotifywait

6) test the access to the docker container
docker exec -it 1e6050215ae echo "Hello from container!"
docker exec -it a1e6050215ae sudo -u www-data /var/www/html/occ files:scan
--all
Starting scan for user 1 out of 6 (Administrator)
Starting scan for user 2 out of 6 (dns-server)
Starting scan for user 3 out of 6 (Guest)
Starting scan for user 4 out of 6 (krbtgt)
Starting scan for user 5 out of 6 (nc_admin)
Starting scan for user 6 out of 6 (ucs-sso)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 15      | 24    | 00:00:00     |
+---------+-------+--------------+

... and all works

7) and finally run sudo systemctl enable --now
nextcloud-inotifyscan@www-data but if i check the systemctl status the
service it's stopped

root@server:/etc/nextcloud-inotifyscan# sudo systemctl status
nextcloud-inotifyscan@www-data
â nextcloud-inotifyscan@www-data.service - Nextcloud inotify scan daemon
for www-data
   Loaded: loaded (/etc/systemd/system/nextcloud-inotifyscan@.service;
enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-05-15 06:11:34 CEST;
3min 53s ago
 Main PID: 20301 (code=exited, status=1/FAILURE)

mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File
"/usr/local/bin/nextcloud-inotifyscan", line 279, in <module>
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:     main()
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File
"/usr/local/bin/nextcloud-inotifyscan", line 274, in main
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:     for task in
watch_instances(parse_args()):
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File
"/usr/local/bin/nextcloud-inotifyscan", line 148, in watch_instances
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:
 universal_newlines=True).rstrip()
mag 15 06:11:34 server nextcloud-inotifyscan[20301]:   File
"/usr/lib/python2.7/subprocess.py", line 219, in check_output
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service:
Main process exited, code=exited, status=1/FAILURE
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service:
Unit entered failed state.
mag 15 06:11:34 server systemd[1]: nextcloud-inotifyscan@www-data.service:
Failed with result 'exit-code'.

i'm apologize but it's two day i fight without any result



Thanks



Il giorno lun 13 mag 2019 alle ore 21:16 Blaok <notifications@github.com>
ha scritto:
